apiVersion: v1
kind: Service
metadata:
  name: croc-hunter-s1
  labels:
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: croc-hunter-s1
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: croc-hunter-s1
  labels:
    app: croc-hunter-s1
spec:
  containers:
    - name: croc-hunter
      image: quay.io/lachie83/croc-hunter:v1
      ports:
        - containerPort: 8080